import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree, Poppins } from "next/font/google";
import DockNav from "@/components/ui/DockNav";
import StaggeredMenu from "@/components/ui/StaggeredMenu";
import GhostCursor from "@/components/ui/GhostCursor";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
});
export const metadata: Metadata = {
  title: "m0hdi1",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} ${poppins.variable} antialiased`}>
        {children}

        {/* Dock navigation for desktop */}
        <DockNav />
        {/* Mobile hamburger */}
        <div className="fixed right-4 top-4 z-50 md:hidden">
          <StaggeredMenu />
        </div>
        {/* Ghost Cursor */}
        <GhostCursor />
      </body>
    </html>
  );
}
